language: bash
arch:
  - arm64
services:
  - docker
script:
  - docker build -t chrisjohnson00/radarr_stephenlu_filter -f Dockerfile .
  - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
  - docker push chrisjohnson00/radarr_stephenlu_filter
