language: bash
arch:
  - amd64
services:
  - docker
jobs:
  include:
    - stage: build branch
      script:
        - docker build -t chrisjohnson00/radarr_stephenlu_filter -f Dockerfile .
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/radarr_stephenlu_filter chrisjohnson00/radarr_stephenlu_filter:$TRAVIS_BRANCH
        - docker push chrisjohnson00/radarr_stephenlu_filter:$TRAVIS_BRANCH
      if: tag is blank
    - stage: build tag
      script:
        - docker build -t chrisjohnson00/radarr_stephenlu_filter -f Dockerfile .
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/radarr_stephenlu_filter chrisjohnson00/radarr_stephenlu_filter:$TRAVIS_TAG
        - docker push chrisjohnson00/radarr_stephenlu_filter:$TRAVIS_TAG
        - docker push chrisjohnson00/radarr_stephenlu_filter
      if: tag IS present
