image: python:3.7-slim
pipelines:
  default:
    - step:
        caches:
          - pip
          - docker
        script:
          - pip install -r requirements.txt
          - pip install flake8
          - flake8 --max-line-length=120 *.py
          - docker login -u $CANISTER_USER -p $CANISTER_PASSWORD cloud.canister.io:5000
          - docker build -t cloud.canister.io:5000/chrisjohnson00/radarr_stephenlu_filter:$BITBUCKET_BRANCH .
          - docker push cloud.canister.io:5000/chrisjohnson00/radarr_stephenlu_filter:$BITBUCKET_BRANCH
        services:
          - docker
  tags:
    '*':
      - step:
          caches:
            - pip
            - docker
          script:
            - pip install -r requirements.txt
            - pip install flake8
            - flake8 --max-line-length=120 *.py
            - docker login -u $CANISTER_USER -p $CANISTER_PASSWORD cloud.canister.io:5000
            - docker build -t cloud.canister.io:5000/chrisjohnson00/radarr_stephenlu_filter:latest .
            - docker tag cloud.canister.io:5000/chrisjohnson00/radarr_stephenlu_filter:latest cloud.canister.io:5000/chrisjohnson00/radarr_stephenlu_filter:$BITBUCKET_TAG
            - docker push cloud.canister.io:5000/chrisjohnson00/radarr_stephenlu_filter:latest
            - docker push cloud.canister.io:5000/chrisjohnson00/radarr_stephenlu_filter:$BITBUCKET_TAG
          services:
            - docker
