name: 'PR Standards Check'
on:
  pull_request:
    types:
      - 'opened'
      - 'edited'
      - 'reopened'
      - 'synchronize'

jobs:
  check-pr-title:
    name: 'PR Title'
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Install Dependencies'
        run: |
          npm install @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional'], rules: { 'subject-case': [0, 'always', ['sentence-case','lower-case', 'start-case']], 'header-max-length': [2, 'always', 120], 'body-max-line-length': [0, 'always', 120] }};" > commitlint.config.js
      - uses: 'JulienKode/pull-request-name-linter-action@v0.2.0'
  check-pr-commits:
    name: 'PR Commit Messages'
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - name: 'Configure commit lint'
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional'], rules: { 'subject-case': [0, 'always', ['sentence-case','lower-case', 'start-case']], 'header-max-length': [2, 'always', 120], 'body-max-line-length': [0, 'always', 120] }};" > commitlint.config.js
      - uses: 'wagoid/commitlint-github-action@v4.1.9'
  apply-labels:
    name: 'PR Labels'
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Apply Herald rules'
        uses: 'gagoar/use-herald-action@v2.3.0'
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          rulesLocation: '.github/herald_rule_*.json'
          base: 'main'
